name: Simple Workflow Test

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Workflow triggered successfully!"
